"""add_session_state

Revision ID: 8265553ace18
Revises: 4b689ec731b5
Create Date: 2026-08-13 19:24:54.911651

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8265553ace18"
down_revision: str | Sequence[str] | None = "4b689ec731b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("session_state", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "session_state")
    # ### end Alembic commands ###
